WIFI_SSID = "REPLACE_WITH_YOUR_SSID"
WIFI_PASSWORD = "REPLACE_WITH_YOUR_SSID"
API_URL = "https://v6.bvg.transport.rest"
FILTERED = []
WALK_DELAY = 300
COLORED = True
SUBWAY_COLORS = True
STATION_ID = 900100003
